lang: ja
title: "諌早市PTA連合会広報紙『諫親』"
description: "諌早市PTA連合会広報紙アーカイブサイトです。"
baseurl: "/kanshin"
url: "https://isahayashi-PTA.github.io"
favicon: images/favicon.png
google_analytics: ""
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Style Guide
    url: /style-guide/
  - text: Tags
    url: /tags/
  - text: Download
    url: https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme

- title: "デジタルブック「諫親」"
  url: /viewer.html
# The shortname for your Disqus site to enable comments.
disqus: justgoodthemes

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy; Scriptor all rights reserved. Theme by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
# 以下のコードを一番最後に追加します
plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
  layout: 'category'
  permalinks:
    category: '/category/:name/'
google_analytics: G-1W1GCTG249
